
services:
  db:
    image: mysql
    restart: always
    env_file:
     - .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_DATABASE}

    ports:
     - "3306:3306"
    volumes:
     - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
     - "8085:80"
    depends_on:
     - db
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
        sh -c "php artisan config:cache &&
             until php artisan migrate; do
               echo 'Waiting for db...'
               sleep 3;
             done &&
             php artisan serve --host=0.0.0.0 --port=8000"
    ports:
        - "8000:8000"
    depends_on:
     - phpmyadmin
    volumes:
     - /var/www/primula/vendor
     - .:/var/www/primula
volumes:
  db_data:





